import { KeywordRule, KeywordDimension } from './types';

/**
 * 关键词拓展规则库示例数据
 * 用途：作为规则库的参考示例，每个维度至少包含2条规则，每条规则包含多个模板
 */

export const RULE_SAMPLES: Record<KeywordDimension, KeywordRule[]> = {
  // 场景维度示例
  scenario: [
    {
      id: 'scenario-sample-1',
      name: '使用场景-前缀（示例）',
      description: '在关键词前添加场景描述（示例规则）',
      dimension: 'scenario',
      patterns: ['{keyword}'],
      templates: [
        '{keyword}怎么用',
        '{keyword}使用方法',
        '{keyword}使用教程',
        '{keyword}使用技巧',
        '如何使用{keyword}',
        '{keyword}怎么用最好',
        '{keyword}使用指南',
        '{keyword}使用步骤',
        '{keyword}使用场景',
        '{keyword}常见用法',
        '{keyword}实用技巧',
        '{keyword}正确使用方法',
        '{keyword}进阶用法',
        '{keyword}高级用法',
        '{keyword}专业用法',
        '{keyword}初学者怎么用',
        '{keyword}入门用法',
        '{keyword}快捷用法',
        '{keyword}日常用法',
        '{keyword}特别用法',
        '{keyword}正确姿势',
        '{keyword}使用流程',
        '{keyword}上手指南',
        '{keyword}实战用法',
      ],
      priority: 1,
    },
    {
      id: 'scenario-sample-2',
      name: '使用场景-后缀（示例）',
      description: '在关键词后添加场景描述（示例规则）',
      dimension: 'scenario',
      patterns: ['{keyword}'],
      templates: [
        '新手用{keyword}',
        '老手用{keyword}',
        '小白用{keyword}',
        '专业用{keyword}',
        '日常用{keyword}',
        '办公用{keyword}',
        '家用{keyword}',
        '学生用{keyword}',
        '商务用{keyword}',
        '旅行用{keyword}',
        '户外用{keyword}',
        '室内用{keyword}',
        '公司用{keyword}',
        '家庭用{keyword}',
        '个人用{keyword}',
        '团队用{keyword}',
        '校园用{keyword}',
        '游戏用{keyword}',
        '设计用{keyword}',
        '剪辑用{keyword}',
        '开发用{keyword}',
        '运营用{keyword}',
      ],
      priority: 2,
    },
  ],

  // 载体维度示例
  carrier: [
    {
      id: 'carrier-sample-1',
      name: '设备载体（示例）',
      description: '关键词使用的设备载体（示例规则）',
      dimension: 'carrier',
      patterns: ['{keyword}'],
      templates: [
        '手机{keyword}',
        '电脑{keyword}',
        '平板{keyword}',
        '笔记本{keyword}',
        '台式机{keyword}',
        'iPhone{keyword}',
        '安卓{keyword}',
        'iPad{keyword}',
        'Mac{keyword}',
        'Windows{keyword}',
        '安卓手机{keyword}',
        '华为手机{keyword}',
        '小米手机{keyword}',
        'OPPO手机{keyword}',
        'vivo手机{keyword}',
        '三星手机{keyword}',
        'Surface{keyword}',
        'Chromebook{keyword}',
        '台式电脑{keyword}',
        '一体机{keyword}',
        '掌机{keyword}',
        '游戏机{keyword}',
      ],
      priority: 1,
    },
    {
      id: 'carrier-sample-2',
      name: '平台载体（示例）',
      description: '关键词使用的平台载体（示例规则）',
      dimension: 'carrier',
      patterns: ['{keyword}'],
      templates: [
        '微信{keyword}',
        '抖音{keyword}',
        '快手{keyword}',
        '小红书{keyword}',
        'B站{keyword}',
        '知乎{keyword}',
        '微博{keyword}',
        '头条{keyword}',
        '淘宝{keyword}',
        '京东{keyword}',
        '拼多多{keyword}',
        '支付宝{keyword}',
        '拼多多{keyword}',
        '美团{keyword}',
        '大众点评{keyword}',
        '腾讯视频{keyword}',
        '爱奇艺{keyword}',
        '优酷{keyword}',
        '哔哩哔哩{keyword}',
        '喜马拉雅{keyword}',
        '网易云音乐{keyword}',
        '酷狗音乐{keyword}',
      ],
      priority: 2,
    },
  ],

  // 状态维度示例
  state: [
    {
      id: 'state-sample-1',
      name: '状态-前缀（示例）',
      description: '在关键词前添加状态描述（示例规则）',
      dimension: 'state',
      patterns: ['{keyword}'],
      templates: [
        '免费的{keyword}',
        '付费的{keyword}',
        '最新{keyword}',
        '热门{keyword}',
        '好用{keyword}',
        '推荐{keyword}',
        '高级{keyword}',
        '专业{keyword}',
        '入门{keyword}',
        '基础{keyword}',
        '进阶{keyword}',
        '简单{keyword}',
        '复杂{keyword}',
        '快速{keyword}',
        '慢速{keyword}',
        '永久免费{keyword}',
        '官方{keyword}',
        '正版{keyword}',
        '破解版{keyword}',
        '绿色版{keyword}',
        '便携版{keyword}',
        '安装版{keyword}',
      ],
      priority: 1,
    },
    {
      id: 'state-sample-2',
      name: '状态-后缀（示例）',
      description: '在关键词后添加状态描述（示例规则）',
      dimension: 'state',
      patterns: ['{keyword}'],
      templates: [
        '{keyword}推荐',
        '{keyword}排行',
        '{keyword}排名',
        '{keyword}对比',
        '{keyword}测评',
        '{keyword}评价',
        '{keyword}评测',
        '{keyword}体验',
        '{keyword}效果',
        '{keyword}怎么样',
        '{keyword}好用吗',
        '{keyword}值得买吗',
        '{keyword}怎么选',
        '{keyword}选哪个好',
        '{keyword}哪个牌子好',
        '{keyword}性价比',
        '{keyword}优惠',
        '{keyword}折扣',
        '{keyword}促销',
        '{keyword}活动',
        '{keyword}特价',
        '{keyword}免费版',
        '{keyword}会员版',
      ],
      priority: 2,
    },
  ],

  // 目标维度示例
  goal: [
    {
      id: 'goal-sample-1',
      name: '学习目标（示例）',
      description: '用户学习的目标（示例规则）',
      dimension: 'goal',
      patterns: ['{keyword}'],
      templates: [
        '学习{keyword}',
        '学会{keyword}',
        '掌握{keyword}',
        '{keyword}入门',
        '{keyword}基础',
        '{keyword}从零开始',
        '{keyword}新手教程',
        '{keyword}自学',
        '如何学习{keyword}',
        '{keyword}怎么学',
        '{keyword}速成',
        '{keyword}快速入门',
        '{keyword}系统学习',
        '{keyword}深度学习',
        '{keyword}进阶学习',
        '{keyword}高级教程',
        '{keyword}精通',
        '{keyword}大神',
        '{keyword}学习路线',
        '{keyword}学习计划',
        '{keyword}学习资料',
        '{keyword}学习资源',
      ],
      priority: 1,
    },
    {
      id: 'goal-sample-2',
      name: '使用目标（示例）',
      description: '用户的使用目标（示例规则）',
      dimension: 'goal',
      patterns: ['{keyword}'],
      templates: [
        '{keyword}赚钱',
        '{keyword}赚钱方法',
        '{keyword}变现',
        '{keyword}副业',
        '{keyword}兼职',
        '用{keyword}赚钱',
        '{keyword}创业',
        '{keyword}就业',
        '{keyword}求职',
        '{keyword}面试',
        '{keyword}职业发展',
        '{keyword}职业规划',
        '{keyword}职业前景',
        '{keyword}转行',
        '{keyword}跳槽',
        '{keyword}升职加薪',
        '{keyword}涨工资',
        '{keyword}自由职业',
        '{keyword}远程工作',
        '{keyword}被动收入',
        '{keyword}睡后收入',
        '{keyword}搞钱',
      ],
      priority: 2,
    },
  ],

  // 方法维度示例
  method: [
    {
      id: 'method-sample-1',
      name: '学习方法（示例）',
      description: '学习某事物的方法（示例规则）',
      dimension: 'method',
      patterns: ['{keyword}'],
      templates: [
        '{keyword}怎么学',
        '怎么学习{keyword}',
        '如何学习{keyword}',
        '{keyword}学习方法',
        '{keyword}学习技巧',
        '{keyword}学习经验',
        '{keyword}学习心得',
        '{keyword}学习步骤',
        '{keyword}学习流程',
        '{keyword}学习路线',
        '{keyword}学习计划',
        '{keyword}学习资源',
        '{keyword}学习材料',
        '{keyword}学习书籍',
        '{keyword}学习视频',
        '{keyword}学习课程',
        '{keyword}笔记',
        '{keyword}思维导图',
        '{keyword}重点',
        '{keyword}难点',
        '{keyword}考试',
        '{keyword}考证',
      ],
      priority: 1,
    },
    {
      id: 'method-sample-2',
      name: '使用方法（示例）',
      description: '使用某事物的方法（示例规则）',
      dimension: 'method',
      patterns: ['{keyword}'],
      templates: [
        '{keyword}怎么用',
        '怎么使用{keyword}',
        '如何使用{keyword}',
        '{keyword}使用方法',
        '{keyword}使用技巧',
        '{keyword}使用心得',
        '{keyword}使用经验',
        '{keyword}操作方法',
        '{keyword}操作步骤',
        '{keyword}操作流程',
        '{keyword}使用教程',
        '{keyword}教学视频',
        '{keyword}演示视频',
        '{keyword}实战教程',
        '{keyword}入门教程',
        '{keyword}进阶教程',
        '{keyword}操作指南',
        '{keyword}快速上手',
        '{keyword}配置教程',
        '{keyword}安装教程',
        '{keyword}卸载教程',
      ],
      priority: 2,
    },
  ],
};
